"""users table

Revision ID: 2cf96409b856
Revises: 1579059d7bd9
Create Date: 2021-06-19 13:30:52.610152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cf96409b856'
down_revision = '1579059d7bd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('desired_temperature', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('address', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_user_address'), 'user', ['address'], unique=False)
    op.create_index(op.f('ix_user_desired_temperature'), 'user', ['desired_temperature'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_desired_temperature'), table_name='user')
    op.drop_index(op.f('ix_user_address'), table_name='user')
    op.drop_column('user', 'address')
    op.drop_column('user', 'desired_temperature')
    # ### end Alembic commands ###
